"""Baseline schema (subscribers, drive_state, broadcast_log, audit_log, admins,
materials_index).

The baseline creates the current model metadata directly so it stays in sync with the ORM;
subsequent migrations should be explicit/autogenerated.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-18
"""

from __future__ import annotations

from alembic import op
from app.repo import models  # noqa: F401 - register tables on the metadata
from app.repo.db import Base

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(op.get_bind())
